apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app1.app_name }}
  labels:
    app: {{ .Values.app1.app_name }}
spec:
  replicas: {{ .Values.app1.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app1.app_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app1.app_name }}
    spec:
      containers:
        - name: {{ .Values.app1.app_name }}
          image: {{ .Values.app1.image.repository }}:{{ .Values.app1.image.tag }}
          ports:
            - containerPort: {{ .Values.app1.containerPort }}