apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app1.app_name }}-service
  labels:
    app: {{ .Values.app1.app_name }}
spec:
  type: {{ .Values.app1.service.type }}
  ports:
    - port: {{ .Values.app1.service.port }}
      targetPort: {{ .Values.app1.containerPort }}
  selector:
    app: {{ .Values.app1.app_name }}